### ISSUE TITLE
Re-export Metrics and Latency

### ISSUE THREAD

**Issue by insanitybit** [selmeci/dgraph-tonic#30]
https://docs.rs/dgraph-tonic/0.8.4/dgraph_tonic/struct.Response.html#structfield.metrics

The Metrics and Latency objects appear to somehow not be exported in a way that is publicly accessible. This means that there's no way to discover them in the documentation, and no way to construct (or destructure) them in code, take them as arguments, etc.

All that's required is a change to this line:
```rust
pub use crate::api::{
    Check, LoginRequest, Mutation, Operation, Payload, Request, Response, TxnContext, Version,
};
```

to include Metrics and Latency.

**Comment by selmeci** [comment]
Hi @insanitybit, thanks for reporting issue.

Metrics and Latency object are available in version 0.8.6
