### ISSUE TITLE
Having trouble connecting to Dgraph cloud

### ISSUE THREAD

**Issue by AnnZ2021** [selmeci/dgraph-tonic#36]
Using dgraph-tonic client having trouble connecting to Dgraph cloud. `thread ‘main’ panicked at 'committed: Dgraph: gRPC communication Error.

Caused by:
Client: cannot commit or abort.
Status { code: Unknown, message: “hash mismatch the claimed startTs|namespace”, metadata: MetadataMap { headers: {“date”: “Tue, 17 May 2022 16:48:10 GMT”, “content-type”: “application/grpc”, “content-length”: “0”, “access-control-allow-credentials”: “true”, “access-control-allow-methods”: “GET,POST,OPTIONS”, “access-control-allow-origin”: “https://cloud.dgraph.io/”, “server”: “Caddy”} } }’`

is it possible to connect through gRPC using the free version?

**Comment by AnnZ2021** [comment]
> Hi,
> 
> 
> 
> what do you mean by Dgraph Cloud? 
> 
> We are using dgraph-tonic and Dgraph dedicated cluster hosted in the cloud.
> 
> Are you using version with feature [slash-ql](https://dgraph.io/slash-graphql)?
> 
> 

I've registered an personal account on Dgraph cloud for free usage. The cluster is hosted in the cloud with an https link along with self managed API token to allow access to it. Yes,I was using version Rust tonic driver lib with feature [slash-ql].

**Comment by selmeci** [comment]
Did you modify connection link according to documentation?
```
If your Slash GraphQL endpoint is https://app.eu-central-1.aws.cloud.dgraph.io/graphql than connection endpoint for gRPC client is http://app.grpc.eu-central-1.aws.cloud.dgraph.io:443
```
