### ISSUE TITLE
Need to be able to control upsert commit now

### ISSUE THREAD

**Issue by lhr0909** [selmeci/dgraph-tonic#7]
We have an upsert operation used in the middle of a transaction, but right now `dgraph-tonic` doesn't allow upsert to control whether or not the txn should be committed or not.

Proposing to add two more upsert operations with `&mut self` and not setting the `commit_now` flag in the request.

Some reference I have in other client implementations:

https://github.com/dgraph-io/dgo#running-an-upsert-query--mutation
https://github.com/dgraph-io/dgraph-js#running-an-upsert-query--mutation

Although the dGraph documentation recommends committing after upsert, we have a long update chain txn that currently will produce wrong side effects if we don't run this upsert in the middle of the txn.

**Comment by lhr0909** [comment]
@selmeci by the way I updated the library to match the latest master of yours and it is working quite well! It should make it easier to work with wrapper other types now. Thanks for the help!

Also I am starting to use async clients and it is working in async scenario.

https://github.com/xanthous-tech/dgraph-js-native

**Comment by selmeci** [comment]
Resolved with https://github.com/selmeci/dgraph-tonic/releases/tag/v0.6.2
